name: Angular_DockerImage_v2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  angular_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: npm install
      run: npm install

    - name: build
      run: |
        npm run build -- --output-path=docs --base-href /
        # Aseguramos que los archivos estén en la raíz de docs
        if [ -d "docs/browser" ]; then mv docs/browser/* docs/ && rm -rf docs/browser; fi

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Download and run the Docker base image
      run: docker run -d --name http_base httpd

    - name: copy app to the Docker image
      run: docker cp docs/. http_base:/usr/local/apache2/htdocs

    - name: Build and Push the custom Docker image
      run: |
        docker commit --change "ENV MODEL_NAME http_base" http_base ${{secrets.DOCKER_USER}}/mycv:latest
        docker push ${{secrets.DOCKER_USER}}/mycv:latest
